version: 2
jobs:
  build:
    working_directory: ~/koa-notes-api
    docker:
      - image: circleci/node:10
        environment:
          MONGO_URI_TEST: $MONGO_URI_TEST
    steps:
      - checkout
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-deps
          command: npm install          
      - run:
          name: test
          command: npm test
