version: 2
jobs:
  build:
    working_directory: ~/koa-notes-api
    docker:
      - image: circleci/node:10
        environment:
          NODE_ENV: test
    steps:
      - checkout
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-deps
          command: npm install
      - run:
          name: test
          command: npm test -- MONGO_URI_TEST=mongodb+srv://andrewmcoupe:Oliver24!!@cluster0-bctzs.mongodb.net/notes-api-test?retryWrites=true&w=majority
